name = "backend"
main = "worker.js"
compatibility_date = "2025-07-18"

[[kv_namespaces]]
binding = "WORLD_CODES"
id = "ece2fad97734483d8275edda2d001f6d"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true







